---
title: "Port Temperature Profiles"
author: "Mitchell Brown, Jonathan Kennel, Jonathan Munn, Beth Parker"
date: "04/02/2022"
output:
  html_document:
    toc: yes
    theme: flatly
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
library(ggplot2)
library(data.table)
library(dplyr)
library(gridExtra)
library(dts)
library(arrow)
library(dplyr)
library(tibble)
library(duckdb)
library(viridis)
library(gam)
library(mgcv)
library(tidyverse)
library(plotly)
library(grid)
library(cowplot)
library(XML)
source("function_mitch_heating_time.R")
source("function_get_heating_data.R")
source("function_to_data_table.R")
source("function_interpolate_XT_Ultima.R")
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, warning=FALSE}
setwd("C:/Users/Mitchell/Desktop/Thesis Data/rawSenData/SEN6")

inputs <- c("2018_MLS/channel_1/out180/dts_data/dts.rds",
         "2019_05_MLS/channel_1/out180/dts_data/dts.rds",
         "2021_08_MLS/channel_1/out180/dts_data/dts.rds",
         "2019_10_MLS/channel_1/out180/dts_data/dts.rds",
         "2020_02_MLS/channel_2/out180/dts_data/dts.rds",
         "2021_02_MLS/channel_2/out180/dts_data/dts.rds")

ports <- read.csv("C:/Users/Mitchell/Desktop/Thesis Data/rawSenData/SEN6/ports.csv")
ports <- ports[1:9,]
ports$TopDepth <- ports[,1] + 0.47
ports$BottomDepth <- ports[,2] + 0.47

# input <- "2021_02_MLS/channel_2/out180/dts_data/dts.rds"

# For loop takes list of inputs and generates temp-time plots for each distance specified
All_data <- data.table()
for (input in inputs) {
  
  # read dts data
  dts <- readRDS(input)
  
  heat <- get_heating_data_1(dts)
  
  if (dts$device$type=="xt") {
    data <- to_data_table(heat, xt=TRUE)
  } else {
    data <- to_data_table(heat, xt=FALSE)
  }
  
  # isolate time
  ten_hour <- data[data$elapsed_time > 0 & elapsed_time < 36000]
  
  # first subset to borehole
  list_of_distances <- colnames(ten_hour)
  list_of_distances <- list_of_distances[c(3:length(list_of_distances))]
  
  ten_nums <- as.double(list_of_distances) - 29.5782
  
  alright <- c("elapsed_time", "log_elapsed_time")
  columns_ <- append(alright, ten_nums)
  colnames(ten_hour) <- columns_
  
  to_subset <- ten_nums >= 5.0 & ten_nums <= 65.55
  index <- which(to_subset == TRUE)
  first <- index[1]
  last <- index[length(index)]
  #add two to account for elapsed time columns
  sub <- subset(ten_hour, select=(first+2):(last+2))
  
  # to subtract the fist row from every row
  sub <- sub %>% mutate_if(is.numeric, funs(.-first(.)))
  
  # format data.table for plotting
  df <- data.table(ten_hour$log_elapsed_time, sub)
  df1 <- melt(df,  measure.vars = colnames(df[,-1]))
  
  
  #split input string to assign a type
  input_split <- strsplit(input, split='/')
  grab_test <- input_split[[1]][1]
  
  df1$type <- grab_test
  All_data <- rbind(All_data, df1) 
}

# make column to filter
dat <- All_data$variable
filters <- as.numeric(levels(dat))[dat]
All_data$filter <- filters

# filter
port1 <- All_data %>% filter(filters >= 20.49, filters <= 22.91)




final <- ggplot(port1, aes(x =V1, y=value, color = type, group = type)) +
          geom_line(aes(color=type)) +
          facet_wrap (variable~., scales="fixed", ncol=5)

# ggplotly(final)
```

```{r echo=FALSE, warning=FALSE}

#READ THERMAL CONDUCTIVITY DATA
setwd("C:/Users/Mitchell/Desktop/Thesis Data/rawSenData/SEN6/Time Intervals - Thermal Conductivity/Middle")

#read in all the data and combine by row
temp = list.files(patter="*.csv")
middle = lapply(temp, read.csv)
names(middle) = c("Aug-2018", "May-2019", "Oct-2019", "Feb-2020", "Feb-2021", "Aug-2021")
alldata <- data.table(bind_rows(middle, .id="test"))

#READ IN PORT DATA
ports <- read.csv("C:/Users/Mitchell/Desktop/Thesis Data/rawSenData/SEN6/ports.csv")
ports <- ports[1:9,]
ports$TopDepth <- ports[,1] + 0.47
ports$BottomDepth <- ports[,2] + 0.47

#INTERPOLATE

interpolated <- data.table(middle[[1]], middle[[2]]$Therm_con, middle[[6]]$Therm_con)

#isolate data we want to interpolate
temp_interpolate = c(temp[3:5])
inter = lapply(temp_interpolate, read.csv)
names(inter) = c("Oct-2019", "Feb-2020", "Feb-2021")

x_interpolate <- middle[[1]]$depth_btoc
for (i in 1:length(inter)) {
  j <- inter[[i]]
  x <- j$depth_btoc
  y <- j$Therm_con
  new <- approx(x,y,xout=x_interpolate)
  interpolated <- cbind(interpolated, new$y)
}

interpolated <- data.table(interpolated)
interpolated <- interpolated[2:533,]
colnames(interpolated) <- c("Depth", "Aug2018", "May2019", "Aug2021", "Oct2019", "Feb2020", "Feb2021")

#Differences
ref <- interpolated$Aug2021
difference <- interpolated
difference$Aug2018 <- difference$Aug2018 - ref
difference$May2019 <- difference$May2019 - ref
difference$Aug2021 <- difference$Aug2021 - ref
difference$Oct2019 <- difference$Oct2019 - ref
difference$Feb2020 <- difference$Feb2020 - ref
difference$Feb2021 <- difference$Feb2021 - ref

```

```{r echo=FALSE, warning=FALSE, fig.width=10, fig.height=6} 
i <- 3

port1 <- interpolated[Depth >= ports$TopDepth[i] & Depth <=ports$BottomDepth[i],]

#to plot all columns, need to reshape data
port1_ggplot <- data.frame(x=port1$Depth,
                                  y=c(port1$Aug2018, port1$May2019,
                                      port1$Aug2021, port1$Oct2019,
                                      port1$Feb2020, port1$Feb2021),
                                  group = c(rep("Aug2018", nrow(port1)),
                                            rep("May2019", nrow(port1)),
                                            rep("Aug2021", nrow(port1)),
                                            rep("Oct2019", nrow(port1)),
                                            rep("Feb2020", nrow(port1)),
                                            rep("Feb2021", nrow(port1))))


port <- ggplot(port1_ggplot, aes(x = x, y = y, col=group)) + 
          geom_line() +
          ylim(c(0, 15)) +
          scale_x_reverse() +
          coord_flip() +
          ggtitle("Thermal Conductivities") +
          ylab("Thermal Conductivity (W/mK)") +
          xlab("Depth Below Ground Surface (m)") +
          theme(legend.title = element_blank())

port <- ggplotly(port)

#port1 difference
port1_diff <- difference[Depth >= ports$TopDepth[i] & Depth <=ports$BottomDepth[i],]

if (max(port1_diff[,2:7] > 5)) 
{top = 15} else 
    {top = 5}

#to plot all columns, need to reshape data
port1_diff_ggplot <- data.frame(x=port1_diff$Depth,
                           y=c(port1_diff$Aug2018, port1_diff$May2019,
                               port1_diff$Aug2021, port1_diff$Oct2019,
                               port1_diff$Feb2020, port1_diff$Feb2021),
                           group = c(rep("Aug2018", nrow(port1_diff)),
                                     rep("May2019", nrow(port1_diff)),
                                     rep("Aug2021", nrow(port1_diff)),
                                     rep("Oct2019", nrow(port1_diff)),
                                     rep("Feb2020", nrow(port1_diff)),
                                     rep("Feb2021", nrow(port1_diff))))



port_diff <- ggplot(port1_diff_ggplot, aes(x = x, y = y, col=group)) + 
                geom_line() +
                ylim(c(-40,top)) +
                scale_x_reverse() +
                coord_flip() +
                ggtitle("Difference in Thermal Conductivty") +
                ylab("Thermal Conductivity (W/mK)") +
                xlab("Depth Below Ground Surface (m)")

port_diff <- ggplotly(port_diff) 

#print(paste0("Port: ", ports$Port[i]))
#print(paste0("Maximum thermal conductivity difference: ", round(max(port1_diff[,2:7]),2)))
#print(paste0("Average thermal conductivity difference: ", mean(port1_diff[,2:7])))
require(gridExtra)
    
subplot(port, port_diff)
ggplotly(final)
#plot_grid(port, port_diff, final, ncol=3, rel_widths = c(1/4, 1/4, 1/2))
    
```









